--For development only - uncomment temporarely when you need it:
begin for i in (select 1 from user_tables where table_name = 'CONSOLE_LOGS') loop execute immediate 'drop table console_logs purge'; end loop; end;
/

declare
  v_name varchar2(30 char) := 'CONSOLE_LOGS';
begin
  for i in (
    select v_name from dual
    minus
    select table_name from user_tables where table_name = v_name
  )
  loop
    execute immediate q'{
      create table console_logs (
        id         integer                         generated by default on null as identity,
        log_time   timestamp with local time zone  default systimestamp  not null,
        log_level  integer,
        message    clob,
        --
        constraint console_logs_check_level check (log_level in (0,1,2,3))
      )
    }';
  end loop;
end;
/